name: Build & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    
    - name: Install NPM packages
      run: yarn install
    
    - name: Build project
      run: yarn run build
      env:
        REACT_APP_KINDLY_URL: ${{ secrets.REACT_APP_KINDLY_URL }}
        REACT_APP_PUBLIC_URL: ${{ secrets.REACT_APP_PUBLIC_URL }}
        REACT_APP_SCRIPT_URL: ${{ secrets.REACT_APP_SCRIPT_URL }}

    - name: Run tests
      run: yarn run test

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./build
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build

    - name: Recreate CNAME
      run: echo kindly.unicef.io > ./build/CNAME

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build